# Generated by Django 6.0.1 on 2026-02-24 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inheritence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstPerson',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inheritence.person')),
            ],
            bases=('inheritence.person',),
        ),
    ]
