# Generated by Django 6.0.1 on 2026-02-17 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0001_initial'),
        ('signal_app', '0003_profile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='address_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pin_code', models.IntegerField()),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Adduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpage.adduser')),
            ],
        ),
    ]
