# Generated by Django 6.0.1 on 2026-02-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signal_app', '0004_address_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address_list',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='address_list',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='address_list',
            old_name='Pin_code',
            new_name='pin_code',
        ),
        migrations.RenameField(
            model_name='address_list',
            old_name='State',
            new_name='state',
        ),
    ]
