# Generated by Django 6.0.1 on 2026-02-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0001_initial'),
        ('signal_app', '0005_rename_city_address_list_city_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='address_list',
            new_name='AddressList',
        ),
        migrations.RenameField(
            model_name='addresslist',
            old_name='Adduser',
            new_name='adduser',
        ),
    ]
