# Generated by Django 6.0.1 on 2026-02-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_app', '0007_useraddresslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddresslist',
            name='city',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useraddresslist',
            name='country',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useraddresslist',
            name='pin_code',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='useraddresslist',
            name='state',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
