# Generated by Django 5.2.11 on 2026-02-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0002_alter_adduser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
