# Generated by Django 6.0.1 on 2026-02-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_product_user_delete_snippet_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Fashion',
            field=models.CharField(default='INDIAN TERRAIN', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_ava',
            field=models.IntegerField(default=50),
        ),
    ]
