# Generated by Django 6.0.1 on 2026-02-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_fashion_product_quantity_ava'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='Quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity_ava',
            new_name='Quantity_ava',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='tax_per',
            new_name='Tax_per',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='User_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='User_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contect_info',
        ),
        migrations.AddField(
            model_name='user',
            name='Contect_info',
            field=models.IntegerField(default=9999999999),
            preserve_default=False,
        ),
    ]
