# Generated by Django 6.0.1 on 2026-02-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_quantity_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Fashion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='Quantity_ava',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='Tax_per',
            field=models.FloatField(default=18),
        ),
        migrations.AlterField(
            model_name='user',
            name='Contect_info',
            field=models.IntegerField(default=999999999),
        ),
    ]
