# Generated by Django 6.0.1 on 2026-02-10 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_product_fashion_alter_product_quantity_ava_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductO', to='api.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserO', to='api.user'),
        ),
    ]
