# Generated by Django 6.0.1 on 2026-02-12 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_pizza_topping_restaurant_pizza_toppings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='best_pizza',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='pizzas',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
