# Generated by Django 6.0.1 on 2026-01-15 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_choice_question_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='students',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
