# Generated by Django 6.0.1 on 2026-01-15 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_question_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
    ]
