# Generated by Django 6.0.1 on 2026-01-15 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_question_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['-votes']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_text']},
        ),
    ]
