# Generated by Django 6.0.1 on 2026-01-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_choice_options_alter_question_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
