# Generated by Django 6.0.1 on 2026-01-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_choice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('choice_text', 'votes')},
        ),
    ]
