# Generated by Django 6.0.1 on 2026-01-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_author_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(blank=True, help_text='Enter question', max_length=200, verbose_name='enter'),
        ),
    ]
