# Generated by Django 6.0.1 on 2026-01-28 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('about', models.TextField(default='this is good book', verbose_name='about book')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.sales')),
            ],
        ),
    ]
