# Generated by Django 6.0.1 on 2026-01-29 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sales',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.sales'),
        ),
    ]
